version: '3.9'

services:
  
  mysql:
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html 
    links:
        - php

  php:
    restart: always
    image: php:7.4-fpm-alpine
    volumes:
      - ./data/html:/var/www/html 

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
        ports:
            - "8081:80"
        restart: always
