version: '3.9'

services:
  
  database:
    restart: always
    image: mysql:${DB_VERSION:-latest}
    container_name: mysql-mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-db}
      MYSQL_USER: ${DB_USER:-dbuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}

  nginx:
    restart: always
    image: nginx:${NGINX_VERSION:-stable-alpine}
    ports:
      - 80:80
    volumes:
      - ./config/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html 
    links:
        - php

  php:
    restart: always
    image: php:${PHP_VERSION:-7.4-fpm-alpine}
    volumes:
      - ./data/html:/var/www/html 

  phpmyadmin:
        image: phpmyadmin/phpmyadmin:${PMA_VERSION:-latest}
        environment:
            PMA_HOST: database
            PMA_USER: ${DB_USER:-dbuser}
            PMA_PASSWORD: ${DB_PASSWORD:-secret}
        ports:
            - "8081:80"
        restart: always
